### ISSUE TITLE
[BUG] Overshoot of planned maneuver burn (burned too long)

### ISSUE THREAD

**Issue by schlosrat** [cfloutier/k2d2#1]
I was using K2-D2 to execute a maneuver I'd set up using Maneuver Node Controller for a Munar encounter that would bring me in with a periapsis around 50km. Once the maneuver node was set up (868.37 m/s Delta-v all in prograde with a start time configured to give me the Munar encounter I wanted), I used K2-D2 to execute the node.

K2D@ got my craft pointed correctly, time-warped to the node, and kicked off the burn, but the burn badly overshot the encounter and I had to press the Stop button. As you can see in the image attached, the burn time got to 00, but there's some white bar in the burn slider and now I'm on an impact mission instead of a close fly-by. Had I not stopped K2-D2 I'm unsure haw far it would have overshot and I might have gotten on a trajectory to encounter the Mun in a retrograde orbit.

Is K2-D2 not able to accurately stop the burn? Perhaps the throttle can be tuned down as the end of the burn approaches for a more accurate application of the required Delta-v?

![K2-D2 overshoot](https://user-images.githubusercontent.com/50781429/226743822-67572bef-6dfa-4776-9135-2b5c5c35b018.png)

**Comment by cfloutier** [comment]
I hopes it's better with 0.5.0 version based on real dv

**Comment by cfloutier** [comment]
I thinks the trouble is no more found in last version. reopen it @schlosrat if you find it again.
thans again for the report

**Comment by cfloutier** [comment]
totally rewrote the burn value

**Comment by cfloutier** [comment]
I think the 0.7.1 corrected the trouble

**Comment by schlosrat** [comment]
This looks solved to me. I'll mark it closed.
