### ISSUE TITLE
UI Layer ordering

### ISSUE THREAD

**Issue by JustinSchneider** [cfloutier/k2d2#15]
K2-D2 renders on top of the app menu, forcing me to move it out of the bottom corner when I need to access another app. Could you have its layer order adjusted to be similar to other panels? Flight Plan seems to be set correctly.

![image](https://github.com/cfloutier/k2d2/assets/4027412/3545fc6e-97b2-42cb-91b3-a3c6680dcc20)

Loving the improvements to K2! Haven't had a node fail to process since the last update.

**Comment by JustinSchneider** [comment]
Additionally, although the K2-D2 window renders on top of  other windows (such as DAD or Flight Plan), click events are not being caught by K2-D2 and instead are being captured by the background window. Not sure which asset may be at fault, there, as it may be greedy consumption of mouse events on their part.

**Comment by cfloutier** [comment]
It has been corrected with the last version. 
1.0 version uses UITK now like FlightPlan

**Comment by cfloutier** [comment]
I close it
