### ISSUE TITLE
[Bug] Timewarp overshoot of maneuver node (skipped node entirely)

### ISSUE THREAD

**Issue by schlosrat** [cfloutier/k2d2#2]
I manually trimmed the Mun encountered I described in the previous bug report so that I'd get a Pe of about 60km in a prograde hyperbolic orbit of the Mun. I then used Maneuver Node Controller to set up a precise node on the periapsis to circularize my orbit. With that node set up, I pressed Run on K2-D2 and it time-warped my craft right past the node only stopping the time warp once I was outbound from the Mun. It consequently never even lit the engines as the game removed the node once we were past it.

So, in the previous bug report, K2-D2 burned to long, overshooting the end of the burn, and in this one it time-warped right past the burn and so never even started it.

![K2-D2 overshoot2](https://user-images.githubusercontent.com/50781429/226745966-94100b5f-85bd-4049-aab4-9b9e42129ad0.png)

**Comment by cfloutier** [comment]
The warp ratio. Should be under 3. I'll add a min value in settings

**Comment by cfloutier** [comment]
Thanks for the report @schlosrat

**Comment by cfloutier** [comment]
I've met other cases : 
Burn has started at the very wrong time. (start of timewarp phase). like if timewarp is skipped because maneuver is in the past and the same for the burn.... I need to do more check.

**Comment by cfloutier** [comment]
no more reproduced in last version v0.7.0. the node is no more updated during execute

**Comment by schlosrat** [comment]
This looks solved to me. I'll mark it closed.

**Comment by cfloutier** [comment]
thanks
