### ISSUE TITLE
errors in logs when removing a node. 

### ISSUE THREAD

**Issue by cfloutier** [cfloutier/k2d2#5]
I still need to find a good way to reproduce it. 

![image](https://user-images.githubusercontent.com/11272483/228916543-851323ae-319f-468e-ac42-4442d125d8ed.png)

it seems to happens if we delete a node using the standard kSP2 way.

**Comment by schlosrat** [comment]
I don't think I've seen this in the current version. Perhaps it can be closed?

If you'd like to integrate with Node Manager then I believe it can also be solved that way, but that may not be needed.

**Comment by cfloutier** [comment]
I'll add Node Manager in a near future, usefull to auto delete the node after burn
